name: Upload Artifact

on:
  push:
    branches:
      - main  # Run this action when there's a push to the main branch
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  tar_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create tar.gz archive
        run: |
          tar -czf kkloud-cli.tar.gz -C ./kkloud-cli .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kkloud-cli
          path: kkloud-cli.tar.gz

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.1
          release_name: Release v1.0.1 
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload artifact to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.1
          files: kkloud-cli.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Update Release Description
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.1  # Must match the tag in the previous steps
          release_name: Release v1.0.1  # Ensure this matches your release name
          body: |
            ## Artifact Download
            You can download the artifact from the following link:

            [Download folder_archive.tar.gz](https://github.com/${{ github.repository }}/releases/download/v1.0.1/folder_archive.tar.gz)
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
